### ISSUE TITLE
Loading should  disable page

### ISSUE THREAD

**Issue by matijas-1987** [openbmc/webui-vue#15]
**Describe the bug**
When switching tabs/pages loading bar should disable page for user to not be able to change options.  
Otherwise if user will type in something - option is reset or validation is not done properly.

![loading](https://user-images.githubusercontent.com/66257423/87780182-7e39f600-c82e-11ea-81b1-ae2d09ccba40.gif)

**Comment by derick-montague** [comment]
@yoshiemuranaka @gtmills @ParishrutB @ben-bacon  - This is another reason the angular design had the loading spinner. Can I get your feedback, please?

**Comment by ben-bacon** [comment]
My initial thought it to load a skeleton state for the fields. But if we are not doing that currently in the product elsewhere, then maybe we shouldn't put it in just for this page. Hiding the field titles or disabling the fields until the product fully loads sounds like another option?

**Comment by derick-montague** [comment]
> My initial thought it to load a skeleton state for the fields
This is something that we wanted and thought about doing that I think that is a viable option. Since we have the progress bar, it shouldn't be a stretch for the user to know that something is happening and why they can't interact with the page. 

However, I do think that with pages like Hardware Inventory and Sensors, information is loaded as received from different API calls. That is not a great experience and having a skeleton screen would be a great option for those pages also.

**Comment by ParishrutB** [comment]
> My initial thought it to load a skeleton state for the fields. But if we are not doing that currently in the product elsewhere, then maybe we shouldn't put it in just for this page. Hiding the field titles or disabling the fields until the product fully loads sounds like another option?

Disabling the fields is a pattern which I found in firmware update:
Old prototype: https://ibm.invisionapp.com/d/main#/console/15348054/319289244/preview
New prototype: https://ibm.invisionapp.com/d/main#/console/15364725/319627540/preview
But this seems to work in scenarios where a page is already loaded, and a process is going on. 

Skeleton states are used (in my observation) for when a page is loading afresh. 

The scenario which Matijas has pointed out, is it the one in which a process is going on on the page or one in which the page is reloading? It looks like a page refresh (hence, page loading). For this scenario, skeleton seems to be apropriate. If not a skeleton, then a full page overlay.

**Comment by ParishrutB** [comment]
References from Carbon:
1. Skeleton states: mostly for loading pages. 
2. Spinners/progress bars: mostly for ongoing processes. Depending on scenario, use a different type of spinner or progress bar.
3. Disabled states: Carbon didn't say anything about using them for loading states. Perhaps we are misusing them in case of firmware as well. 

Seems like me might need to put more thought on these patterns as well later on. But for the problem here, skeleton states sound about right. 

https://www.carbondesignsystem.com/patterns/loading-pattern
P.S. also look at Progressive Loading.

**Comment by lukkep** [comment]
I believe that progressing loading is OK for controls like grids, where user does not put content into. 
When comes to load controls like text boxes which can be edited and have previous content - that's the issue I believe, because user might edit content that is not loaded yet and it will be replaced.

My opinion is that disabling controls until loaded sounds good enough. 🙄

**Comment by yoshiemuranaka** [comment]
I agree, I think disabling any form fields that are visible on initial page load would be sufficient. Currently that would be on
- Network settings
- Date and time
- LDAP
- Manage power usage

Suren is also working on a story this sprint that will add a default empty table state (currently only implemented on event logs) to all other tables, which would be an improved experience for hardware status and sensors like you mentioned @derick-montague

**Comment by matijas-1987** [comment]
@derick-montague @yoshiemuranaka  I have prepared commit with disabling any form fields.
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35095
