### ISSUE TITLE
KVM Layout updates

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#24]
**Is your feature request related to a problem? Please describe.**
Layout consistency between KVM and SOL were discussed in the GUI Design Workgroup on 7/22/20. The following changes were agreed upon during the session.

**Describe the solution you'd like**

- [ ] Update the section description to include what the KVM acronym stands for, Keyboard, Video (monitor), Mouse
- [ ] Add helper text
- [ ] Bold the Status label and code semantically as a definition list
- [ ] Add the icon for connected or disconnected
- [ ] Move actions to the top right aligned with the terminal
- [ ] Make the terminal square and fit within viewport
    - [ ] Should include horizontal scrollbar at medium breakpoint (Bootstrap based grid breakpoints). Medium breakpoint is a suggestion that can be explored
- [ ] Update KVM navigation text to `KVM console`
- [ ] In new window, add consistent left and right margins between text and [browser chrome](https://www.pcmag.com/encyclopedia/term/browser-chrome).

![image](https://user-images.githubusercontent.com/1183515/88232858-3a832a00-cc3c-11ea-9086-d93115766413.png)

**Comment by derick-montague** [comment]
@matijas-1987 we are starting #25 this sprint to meet the consistency requirements we agreed to.

**Comment by matijas-1987** [comment]
@derick-montague , please assign to me this task

**Comment by derick-montague** [comment]
We may want to discuss the challenges of a square window from a responsive perspective. It will be challenging to do this without adding scroll bars to either the browser viewport or the the window itself. We are working through this on #25.

**Comment by matijas-1987** [comment]
I have prepared KVM version which is responsive and without adding scroll bars. However it isn't a square. Maybe the square is not a good idea. Below I have added 3 screens of KVM in 3 resolutions (my notebook, monitor and phone). 
I have removed helper text and description, only title exists because in small resolutions the KVM window was too small.
What do you think about it?

<img width="957" alt="my-monitor" src="https://user-images.githubusercontent.com/66257423/92238526-be763600-eeb9-11ea-8c5b-0fb70ae05c97.png">

<img width="964" alt="my-notebook" src="https://user-images.githubusercontent.com/66257423/92238530-c0d89000-eeb9-11ea-8719-678eb9376e98.png">

<img width="203" alt="my-phone" src="https://user-images.githubusercontent.com/66257423/92238538-c3d38080-eeb9-11ea-89ce-c4bfb787e3b3.png">

**Comment by derick-montague** [comment]
These look great @matijas-1987! @Srisuk - This is the direction we can go to avoid the square issue.

**Comment by derick-montague** [comment]
@matijas-1987 - we would need to try and keep the action buttons aligned with the terminal window.

**Comment by matijas-1987** [comment]
@derick-montague , of course. I'm working on it.
